# Generated by Django 4.2.8 on 2024-10-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='services_stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
