# Generated by Django 4.2.8 on 2024-12-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activation',
            name='mfa_token',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
